version: "3.9"
services:
  prediction-api:
    build:
      context: .
      dockerfile: src/docker/prediction_api.Dockerfile
    environment:
      PREDICTION_ENDPOINT: "http://prediction-server:8080"
    ports:
      - "8082:8082"
    depends_on:
      - prediction-server
  prediction-server:
    image: "levan.home:5000/waterbowl/prediction-server:latest"
    ports:
      - "8080:8080"
    environment:
      PREDICTION_API_MODEL_REPOSITORY_PATH: "/opt/ml/model/model.mlpkg"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
