# Default values for prediction-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

api:
  image:
    repository: levan.home:5000/waterbowl/prediction-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  environment:
    - name: PRODUCTION_MODEL_ID
      value: "squak-squak"

prediction:
  image:
    repository: levan.home:5000/waterbowl/prediction-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  environment:
    - name: PREDICTION_API_MODEL_REPOSITORY_PATH
      value: "/opt/ml/model/model.mlpkg"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: waterbowl-prediction-api-prediction-api-middleware@kubernetescrd
    traefik.ingress.kubernetes.io/cors-allow-methods: GET,POST
  hosts:
    - host: levan.home
      paths:
        - path: /api/waterbowl/v1/predictions
          pathType: ImplementationSpecific
  middleware:
    prefix: "/api/waterbowl/v1/predictions"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    nvidia.com/gpu: 1
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector:
  beta.kubernetes.io/arch: amd64
  kubernetes.io/arch: amd64

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule


affinity: {}
